### ISSUE TITLE
Support for Bitext mining?

### ISSUE THREAD

**Issue by LukeTu** [thompsonb/vecalign#1]
Thanks for your great work!

I am wondering whether vecalign supports bitext mining, i.e. find all parallel texts while ignoring sentence order. 

Our research focuses on the translation of Wikipedia. However it's quite difficult to have a correct alignment since many sentences that are going to be aligned is shuffled in the article.

I will be very grateful if you could help me out.

**Comment by thompsonb** [comment]
No, this tool is just for sentence alignment, where you assume that documents are at least approximately in order. It sounds like you just want to use LASER, or if you just need the data, see  https://ai.facebook.com/blog/wikimatrix/
