### ISSUE TITLE
Question: about "failed to find overlap=3, will use random vector"

### ISSUE THREAD

**Issue by stet-stet** [thompsonb/vecalign#3]
**Thank you for the awesome tool!**

I ran `overlap.py` with `-n 2`, then ran vecalign.py with `--alignment-max-size 3`, out of fear that LASER may take too much time. This gave me `failed to find overlap=3, will use random vector` for every single line in the original text, which makes sense, but....

**First Question**:
I am curious of the morale behind using random vectors in place of overlap=3 embeddings not present. Or is this actually closer to an arbitrary choice, because overlap embedding not being present is actually something that should not happen?

**Second Question**:
Once again, I am running with `--alignment-max-size 3`. Surely the code looks at (0,3) (3,0) pairs as a possibility, along with (1,2) (2,1) (1,1), else they would not require overlap=3 embeddings. But where and why are (0,3) (3,0) being considered? surely (0,3) and (3,0) is not in `final_alignment_types` produced by the function `make_alignment_types`. 

Actually, why are (0,3) and (3,0) being considered? Is considering (0,2) (0,1) (1,0) (2,0) just not enough?

**Comment by thompsonb** [comment]
The decision to use random vectors (as opposed to crashing) was done in case a few sentences did not have embeddings (e.g. someone might filter out very long sentences). Running with a mismatch between overlaps.py -n and --alignment-max-size is not advised.

The dynamic programming algorithm only considers (0,1) and (1,0) insertions/deletions.
