### ISSUE TITLE
show alignments

### ISSUE THREAD

**Issue by virgulvirgul** [thompsonb/vecalign#4]
I can see just lines on stdout, how can I see the produced alignments and export to a file? 
Thanks for the your efforts.

**Comment by thompsonb** [comment]
I'm not sure I understand your question - can you post the command you are running and the terminal output you get?

**Comment by virgulvirgul** [comment]
I got results form of like as you shown:

```
[0]:[0]:0.156006
[1]:[1]:0.160997
[2]:[2]:0.217155
```

But is there any chance to get like this:

```
Source sentence : target sentence : score
and so on...
```

**Comment by thompsonb** [comment]
The code doesn't produce that format directly, but the output gives the sentence indexes into each document, so you can easily convert it to the format you want.
