### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by leileilin** [thompsonb/vecalign#7]
Hello, I'm thinking, besides using the command line, can you use other methods to call your toolkit? I want to wrap it into a function and call it conveniently. Do you have any suggestions?

**Comment by tamohannes** [comment]
As far as I am concerned, they do not provide such functionality. I suggest you simply import all the packages that they use and make the calls on your own.
For example, in the case of **vecalign.py** file you can do something like this:

```
...
from dp_utils import make_alignment_types, print_alignments, read_alignments, \
    read_in_embeddings, make_doc_embedding, vecalign

from score import score_multiple, log_final_scores
...
      src_sent2line, src_line_embeddings = read_in_embeddings(src_embed[0], src_embed[1])
      tgt_sent2line, tgt_line_embeddings = read_in_embeddings(tgt_embed[0], tgt_embed[1])
...
```

The idea is to get rid of **argparse** attributes and use your custom function parameters.

**Comment by leileilin** [comment]
> As far as I am concerned, they do not provide such functionality. I suggest you simply import all the packages that they use and make the calls on your own.
> For example, in the case of **vecalign.py** file you can do something like this:
> 
> ```
> ...
> from dp_utils import make_alignment_types, print_alignments, read_alignments, \
>     read_in_embeddings, make_doc_embedding, vecalign
> 
> from score import score_multiple, log_final_scores
> ...
>       src_sent2line, src_line_embeddings = read_in_embeddings(src_embed[0], src_embed[1])
>       tgt_sent2line, tgt_line_embeddings = read_in_embeddings(tgt_embed[0], tgt_embed[1])
> ...
> ```
> 
> The idea is to get rid of **argparse** attributes and use your custom function parameters.

thank you man.
i have done that.
